name: Bump App Version

on:
    workflow_dispatch:
        branches:
            - master
        inputs:
            majority:
                description: 'Version majority'
                required: true
                default: patch
                type: choice
                options:
                    - patch
                    - minor
                    - major

jobs:
    bump-version:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3
                with:
                    ref: ${{ inputs.refToBuild }}
                    token: ${{ secrets.REPO_PAT }}

            -   name: Bump app version
                run: |
                    git config user.name "${{ github.actor }}"
                    git config user.email "${{ github.actor }}@users.noreply.github.com"
                    yarn version --${{ inputs.majority }}
                    git push --follow-tags
