name: CI

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2

            -   name: Set up Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: 16

            -   name: Install dependencies
                run: yarn install

            -   name: Build project
                run: yarn build

            -   name: Run unit tests
                run: yarn test unit

            -   name: Run integration tests
                run: yarn test int

            -   name: Bump app version
                run: |
                    git config user.name "${{ github.actor }}"
                    git config user.email "${{ github.actor }}@users.noreply.github.com"
                    yarn version --patch
                    git push --follow-tags

            -   name: Login to Docker Hub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Build and push Docker image
                run: |
                    docker build -t quipex/monobot:latest -t quipex/monobot:${{ github.sha }} .
                    docker push quipex/monobot --all-tags
