name: Create Docker Image

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2

            -   name: Set env
                run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

            -   name: Install dependencies
                run: yarn install

            -   name: Build project
                run: yarn build

            -   name: Login to Docker Hub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Build and push Docker image
                run: |
                    docker build -t quipex/monobot:latest -t quipex/monobot:${{ env.RELEASE_VERSION }} .
                    docker push quipex/monobot --all-tags
